import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Hero from "../components/Hero";

export default function Home() {
  return (
    <div >
      <Head>
        <title> Landing </title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div className='bg-bgcolor-500'>
        <Hero /> 
      </div>
      fdfds

      <footer >
        
      </footer>
    </div>
  )
}
